### ISSUE TITLE
Test failure in master build

### ISSUE THREAD

**Issue by IvanElenskiy** [jupp0r/prometheus-cpp#345] opened 2020-03-12 08:40 UTC
Ubuntu 20.04 Docker container
```
root@58ffffdd4b21:/workspaces/prometheus-cpp/_build# ctest -V
UpdateCTestConfiguration  from :/workspaces/prometheus-cpp/_build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/workspaces/prometheus-cpp/_build/DartConfiguration.tcl
Test project /workspaces/prometheus-cpp/_build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: prometheus_core_test

1: Test command: /workspaces/prometheus-cpp/_build/bin/prometheus_core_test
1: Test timeout computed to be: 10000000
1: Running main() from gmock_main.cc
1: [==========] Running 77 tests from 11 test suites.
1: [----------] Global test environment set-up.
1: [----------] 4 tests from BuilderTest
1: [ RUN      ] BuilderTest.build_counter
1: [       OK ] BuilderTest.build_counter (2 ms)
1: [ RUN      ] BuilderTest.build_gauge
1: [       OK ] BuilderTest.build_gauge (1 ms)
1: [ RUN      ] BuilderTest.build_histogram
1: [       OK ] BuilderTest.build_histogram (0 ms)
1: [ RUN      ] BuilderTest.build_summary
1: [       OK ] BuilderTest.build_summary (0 ms)
1: [----------] 4 tests from BuilderTest (3 ms total)
1: 
1: [----------] 6 tests from CheckNamesTest
1: [ RUN      ] CheckNamesTest.empty_metric_name
1: [       OK ] CheckNamesTest.empty_metric_name (0 ms)
1: [ RUN      ] CheckNamesTest.good_metric_name
1: [       OK ] CheckNamesTest.good_metric_name (1 ms)
1: [ RUN      ] CheckNamesTest.reserved_metric_name
1: [       OK ] CheckNamesTest.reserved_metric_name (0 ms)
1: [ RUN      ] CheckNamesTest.empty_label_name
1: [       OK ] CheckNamesTest.empty_label_name (0 ms)
1: [ RUN      ] CheckNamesTest.good_label_name
1: [       OK ] CheckNamesTest.good_label_name (0 ms)
1: [ RUN      ] CheckNamesTest.reserved_label_name
1: [       OK ] CheckNamesTest.reserved_label_name (0 ms)
1: [----------] 6 tests from CheckNamesTest (1 ms total)
1: 
1: [----------] 5 tests from CounterTest
1: [ RUN      ] CounterTest.initialize_with_zero
1: [       OK ] CounterTest.initialize_with_zero (0 ms)
1: [ RUN      ] CounterTest.inc
1: [       OK ] CounterTest.inc (0 ms)
1: [ RUN      ] CounterTest.inc_number
1: [       OK ] CounterTest.inc_number (0 ms)
1: [ RUN      ] CounterTest.inc_multiple
1: [       OK ] CounterTest.inc_multiple (0 ms)
1: [ RUN      ] CounterTest.inc_negative_value
1: [       OK ] CounterTest.inc_negative_value (0 ms)
1: [----------] 5 tests from CounterTest (0 ms total)
1: 
1: [----------] 8 tests from FamilyTest
1: [ RUN      ] FamilyTest.labels
1: [       OK ] FamilyTest.labels (0 ms)
1: [ RUN      ] FamilyTest.counter_value
1: [       OK ] FamilyTest.counter_value (0 ms)
1: [ RUN      ] FamilyTest.remove
1: [       OK ] FamilyTest.remove (1 ms)
1: [ RUN      ] FamilyTest.removeUnknownMetricMustNotCrash
1: [       OK ] FamilyTest.removeUnknownMetricMustNotCrash (0 ms)
1: [ RUN      ] FamilyTest.Histogram
1: [       OK ] FamilyTest.Histogram (0 ms)
1: [ RUN      ] FamilyTest.add_twice
1: [       OK ] FamilyTest.add_twice (0 ms)
1: [ RUN      ] FamilyTest.should_assert_on_invalid_metric_name
1: [       OK ] FamilyTest.should_assert_on_invalid_metric_name (3 ms)
1: [ RUN      ] FamilyTest.should_assert_on_invalid_labels
1: [       OK ] FamilyTest.should_assert_on_invalid_labels (2 ms)
1: [----------] 8 tests from FamilyTest (6 ms total)
1: 
1: [----------] 11 tests from GaugeTest
1: [ RUN      ] GaugeTest.initialize_with_zero
1: [       OK ] GaugeTest.initialize_with_zero (0 ms)
1: [ RUN      ] GaugeTest.inc
1: [       OK ] GaugeTest.inc (0 ms)
1: [ RUN      ] GaugeTest.inc_number
1: [       OK ] GaugeTest.inc_number (0 ms)
1: [ RUN      ] GaugeTest.inc_multiple
1: [       OK ] GaugeTest.inc_multiple (0 ms)
1: [ RUN      ] GaugeTest.inc_negative_value
1: [       OK ] GaugeTest.inc_negative_value (0 ms)
1: [ RUN      ] GaugeTest.dec
1: [       OK ] GaugeTest.dec (0 ms)
1: [ RUN      ] GaugeTest.dec_negative_value
1: [       OK ] GaugeTest.dec_negative_value (0 ms)
1: [ RUN      ] GaugeTest.dec_number
1: [       OK ] GaugeTest.dec_number (0 ms)
1: [ RUN      ] GaugeTest.set
1: [       OK ] GaugeTest.set (0 ms)
1: [ RUN      ] GaugeTest.set_multiple
1: [       OK ] GaugeTest.set_multiple (0 ms)
1: [ RUN      ] GaugeTest.set_to_current_time
1: [       OK ] GaugeTest.set_to_current_time (0 ms)
1: [----------] 11 tests from GaugeTest (0 ms total)
1: 
1: [----------] 10 tests from HistogramTest
1: [ RUN      ] HistogramTest.initialize_with_zero
1: [       OK ] HistogramTest.initialize_with_zero (0 ms)
1: [ RUN      ] HistogramTest.sample_count
1: [       OK ] HistogramTest.sample_count (0 ms)
1: [ RUN      ] HistogramTest.sample_sum
1: [       OK ] HistogramTest.sample_sum (0 ms)
1: [ RUN      ] HistogramTest.bucket_size
1: [       OK ] HistogramTest.bucket_size (0 ms)
1: [ RUN      ] HistogramTest.bucket_bounds
1: [       OK ] HistogramTest.bucket_bounds (0 ms)
1: [ RUN      ] HistogramTest.bucket_counts_not_reset_by_collection
1: [       OK ] HistogramTest.bucket_counts_not_reset_by_collection (0 ms)
1: [ RUN      ] HistogramTest.cumulative_bucket_count
1: [       OK ] HistogramTest.cumulative_bucket_count (0 ms)
1: [ RUN      ] HistogramTest.observe_multiple_test_bucket_counts
1: [       OK ] HistogramTest.observe_multiple_test_bucket_counts (0 ms)
1: [ RUN      ] HistogramTest.observe_multiple_test_total_sum
1: [       OK ] HistogramTest.observe_multiple_test_total_sum (0 ms)
1: [ RUN      ] HistogramTest.observe_multiple_test_length_error
1: [       OK ] HistogramTest.observe_multiple_test_length_error (0 ms)
1: [----------] 10 tests from HistogramTest (1 ms total)
1: 
1: [----------] 10 tests from RegistryTest
1: [ RUN      ] RegistryTest.collect_single_metric_family
1: [       OK ] RegistryTest.collect_single_metric_family (0 ms)
1: [ RUN      ] RegistryTest.build_histogram_family
1: [       OK ] RegistryTest.build_histogram_family (0 ms)
1: [ RUN      ] RegistryTest.reject_different_type_than_counter
1: [       OK ] RegistryTest.reject_different_type_than_counter (0 ms)
1: [ RUN      ] RegistryTest.reject_different_type_than_gauge
1: [       OK ] RegistryTest.reject_different_type_than_gauge (0 ms)
1: [ RUN      ] RegistryTest.reject_different_type_than_histogram
1: [       OK ] RegistryTest.reject_different_type_than_histogram (0 ms)
1: [ RUN      ] RegistryTest.reject_different_type_than_summary
1: [       OK ] RegistryTest.reject_different_type_than_summary (0 ms)
1: [ RUN      ] RegistryTest.append_same_families
1: [       OK ] RegistryTest.append_same_families (1 ms)
1: [ RUN      ] RegistryTest.throw_for_same_family_name
1: [       OK ] RegistryTest.throw_for_same_family_name (0 ms)
1: [ RUN      ] RegistryTest.merge_same_families
1: [       OK ] RegistryTest.merge_same_families (0 ms)
1: [ RUN      ] RegistryTest.do_not_merge_families_with_different_labels
1: [       OK ] RegistryTest.do_not_merge_families_with_different_labels (0 ms)
1: [----------] 10 tests from RegistryTest (1 ms total)
1: 
1: [----------] 2 tests from SerializerTest
1: [ RUN      ] SerializerTest.shouldSerializeLocaleIndependent
1: /workspaces/prometheus-cpp/core/tests/serializer_test.cc:34: Failure
1: Expected: std::locale::global(std::locale("de_DE.UTF-8")) doesn't throw an exception.
1:   Actual: it throws.
1: [  FAILED  ] SerializerTest.shouldSerializeLocaleIndependent (0 ms)
1: [ RUN      ] SerializerTest.shouldRestoreStreamState
1: [       OK ] SerializerTest.shouldRestoreStreamState (0 ms)
1: [----------] 2 tests from SerializerTest (0 ms total)
1: 
1: [----------] 7 tests from SummaryTest
1: [ RUN      ] SummaryTest.initialize_with_zero
1: [       OK ] SummaryTest.initialize_with_zero (0 ms)
1: [ RUN      ] SummaryTest.sample_count
1: [       OK ] SummaryTest.sample_count (0 ms)
1: [ RUN      ] SummaryTest.sample_sum
1: [       OK ] SummaryTest.sample_sum (0 ms)
1: [ RUN      ] SummaryTest.quantile_size
1: [       OK ] SummaryTest.quantile_size (0 ms)
1: [ RUN      ] SummaryTest.quantile_bounds
1: [       OK ] SummaryTest.quantile_bounds (0 ms)
1: [ RUN      ] SummaryTest.quantile_values
1: [       OK ] SummaryTest.quantile_values (14288 ms)
1: [ RUN      ] SummaryTest.max_age
1: [       OK ] SummaryTest.max_age (1202 ms)
1: [----------] 7 tests from SummaryTest (15491 ms total)
1: 
1: [----------] 11 tests from TextSerializerTest
1: [ RUN      ] TextSerializerTest.shouldSerializeNotANumber
1: [       OK ] TextSerializerTest.shouldSerializeNotANumber (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeNegativeInfinity
1: [       OK ] TextSerializerTest.shouldSerializeNegativeInfinity (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializePositiveInfinity
1: [       OK ] TextSerializerTest.shouldSerializePositiveInfinity (1 ms)
1: [ RUN      ] TextSerializerTest.shouldEscapeBackslash
1: [       OK ] TextSerializerTest.shouldEscapeBackslash (0 ms)
1: [ RUN      ] TextSerializerTest.shouldEscapeNewline
1: [       OK ] TextSerializerTest.shouldEscapeNewline (0 ms)
1: [ RUN      ] TextSerializerTest.shouldEscapeDoubleQuote
1: [       OK ] TextSerializerTest.shouldEscapeDoubleQuote (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeUntyped
1: [       OK ] TextSerializerTest.shouldSerializeUntyped (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeTimestamp
1: [       OK ] TextSerializerTest.shouldSerializeTimestamp (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeHistogramWithNoBuckets
1: [       OK ] TextSerializerTest.shouldSerializeHistogramWithNoBuckets (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeHistogram
1: [       OK ] TextSerializerTest.shouldSerializeHistogram (0 ms)
1: [ RUN      ] TextSerializerTest.shouldSerializeSummary
1: [       OK ] TextSerializerTest.shouldSerializeSummary (1 ms)
1: [----------] 11 tests from TextSerializerTest (2 ms total)
1: 
1: [----------] 3 tests from UtilsTest
1: [ RUN      ] UtilsTest.hash_labels_1
1: [       OK ] UtilsTest.hash_labels_1 (0 ms)
1: [ RUN      ] UtilsTest.hash_labels_2
1: [       OK ] UtilsTest.hash_labels_2 (0 ms)
1: [ RUN      ] UtilsTest.hash_label_3
1: [       OK ] UtilsTest.hash_label_3 (0 ms)
1: [----------] 3 tests from UtilsTest (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 77 tests from 11 test suites ran. (15505 ms total)
1: [  PASSED  ] 76 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] SerializerTest.shouldSerializeLocaleIndependent
1: 
1:  1 FAILED TEST
1/2 Test #1: prometheus_core_test .............***Failed   15.56 sec
test 2
    Start 2: prometheus_pull_test

2: Test command: /workspaces/prometheus-cpp/_build/bin/prometheus_pull_test
2: Test timeout computed to be: 10000000
2: Running main() from gmock_main.cc
2: [==========] Running 1 test from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 1 test from ExposerTest
2: [ RUN      ] ExposerTest.listenOnDistinctPorts
2: [       OK ] ExposerTest.listenOnDistinctPorts (409 ms)
2: [----------] 1 test from ExposerTest (409 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 1 test from 1 test suite ran. (409 ms total)
2: [  PASSED  ] 1 test.
2/2 Test #2: prometheus_pull_test .............   Passed    0.43 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =  16.07 sec

The following tests FAILED:
          1 - prometheus_core_test (Failed)
Errors while running CTest
```

**Comment by gjasny** [comment] 2020-03-12 16:48
This is a duplicate of #330. @jupp0r Do you think we should skip the test if the locale instantiation fails?

**Comment by jupp0r** [comment] 2020-03-12 16:49
Yeah I think so.

**Closed** 2020-03-13 19:23 UTC
