### ISSUE TITLE
issue with cmake -DUSE_THIRDPARTY_LIBRARIES=OFF ..

### ISSUE THREAD

**Issue by yaminisridaran** [jupp0r/prometheus-cpp#162] opened 2018-10-12 08:29 UTC
Hi . I am using prometheus version 0.5.0 
I have created mkdir _build, && cd _build
Inside _build I am executing cmake -DUSE_THIRDPARTY_LIBRARIES=OFF ..

[yamini_sridaran@abdee642ae19 _build]$ cmake -DUSE_THIRDPARTY_LIBRARIES=OFF ..
-- Could NOT find GoogleBenchmark (missing: GoogleBenchmark_LIBRARY GoogleBenchmark_INCLUDE_DIR)
CMake Error at cmake/civetweb-config.cmake:6 (message):
  File or directory
  /src/cna/.build/prometheus/BUILD/prometheus-cpp-0.4.2/3rdparty/civetweb/include
  referenced by variable CIVETWEB_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  cmake/civetweb-config.cmake:10 (set_and_check)
  pull/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!

Can anyone help me please

**Comment by yaminisridaran** [comment] 2018-10-12 19:36
Can anyone please let me know about the above mentioned issue

**Comment by yaminisridaran** [comment] 2018-10-13 16:11
I request to please let me know about the cmake failure mentioned above

**Comment by bdangit** [comment] 2018-10-13 16:16
Hi @yaminisridaran, the error log you shared shows that CMake could not find Civetweb.  It also can’t find Google Benchmark but that is not required in order to build.

Depending on your platform, you should make sure you install Civetweb headers and libs in the appropriate places or you can configure CMake to locate them in a custom location you might have them.

**Comment by gjasny** [comment] 2018-10-13 17:10
The `-DUSE_THIRDPARTY_LIBRARIES=OFF` enabling change (#159) is not merged to master or any release, yet.

**Comment by yaminisridaran** [comment] 2018-10-15 04:58
Thank you. can I know timelines for #159 merge. we dont want to use the third party server. But for now the build to pass I am downloading the third. My understanding is once this flad is enabled. We dont need to download the third party server and build also. Please correct me if I am wrong

**Comment by jupp0r** [comment] 2018-10-16 14:11
@yaminisridaran it's merged to master.

**Comment by yaminisridaran** [comment] 2018-10-17 14:28
lastest tar has it

**Comment by yaminisridaran** [comment] 2018-10-18 07:17
I downloaded the master zip file and tried 

[yamini_sridaran@b016e99adc5a _build]$ cmake DUSE_THIRDPARTY_LIBRARIES=OFF ..
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CivetWeb (missing: CIVETWEB_LIBRARY CIVETWEB_CXX_LIBRARY
  CIVETWEB_INCLUDE_DIR CIVETWEB_CXX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCivetWeb.cmake:31 (find_package_handle_standard_args)
  pull/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/src/cna/prometheus-cpp-master/_build/CMakeFiles/CMakeOutput.log".
See also "/src/cna/prometheus-cpp-master/_build/CMakeFiles/CMakeError.log".

**Comment by hhoffstaette** [comment] 2018-11-04 02:53
@yaminisridaran you obviously need civetweb installed and accessible. Note that the external civetweb
itself must  be built with -DCIVETWEB_ENABLE_CXX=ON, otherwise the CivetServer.h header and
civetweb-cpp library are missing and building prometheus-cpp wil fail. If all those conditions are met
correctly, configuring and building works just fine; I've just done all this and it works.

**Comment by gjasny** [comment] 2018-11-07 20:29
@yaminisridaran Is your issue resolved? Please have a look at [3rdparty/build_for_travis.sh](https://github.com/jupp0r/prometheus-cpp/blob/master/3rdparty/build_for_travis.sh) to see how we build those deps for CI.

**Comment by yaminisridaran** [comment] 2018-11-08 09:13
The issue for me is I cannot use git submodule init because our environement will not gave access to the internet. In your release version I need to do git submodule init and git submodule update to get civetweb sourcecode

**Comment by hhoffstaette** [comment] 2018-11-08 09:30
> The issue for me is I cannot use git submodule init because our environement will not gave access
> to the internet. In your release version I need to do git submodule init and git submodule update
> to get civetweb sourcecode

You don't *have* to use git to pull civetweb - simply download the civetweb tarball and unpack/copy
its contents into the 3rdparty/civetweb directory (without the civetweb-x.y subdirectory).

**Comment by gjasny** [comment] 2018-11-10 08:57
You can use git config url.<base>.insteadOf to replace submodule git urls with ones you mirrored internally. See https://git-scm.com/docs/git-config

I'm closing this issue because it is not a bug in prometheus-cpp.

**Closed by gjasny** 2018-11-10 08:57 UTC
