### ISSUE TITLE
Register/Unregister metric dynamically 

### ISSUE THREAD

**Issue by goudan-er** [jupp0r/prometheus-cpp#346] opened 2020-03-13 04:33 UTC
It seems that there is no such API to unregister a metric.

**Comment by jupp0r** [comment] 2020-03-13 18:06
This is a duplicate of #178. We are still undecided how to proceed with it (I'm leaning towards implementing it). It would be really helpful if you contributed your use case to the discussion on that issue. Thanks!

**Closed by jupp0r** 2020-03-13 18:06 UTC
